FROM node:18-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:18-alpine AS production

WORKDIR /app

COPY --from=build /app/package.json /app/package-lock.json ./
COPY --from=build /app/.next /app/.next
COPY --from=build /app/node_modules /app/node_modules

EXPOSE 3000

CMD ["npm", "run", "start"]
